### PR TITLE
Add support for mongo.Decimal128

### PR DESCRIPTION
**Pull request by artem-konovalov-personal**
There was no ability to use Decimal128 before.
But we really need this one.

### CODE REVIEW

**Comment by nervebassmaster** [comment]
For example this one 
```
[{
"Decimal": { "$decimal128": "42.42" }
}]
```
after running this command `db.example.find()` should be converted in to the following:
```
{ 
  "_id" : ObjectId("5a119807a386932d68b6e585"),
  "Decimal" : NumberDecimal("1.407590507360820E-248")
}
```

**Comment by watson** [comment]
Nice find! Do you mind updating the tests as well to check that this works as expected?

**Comment by nervebassmaster** [comment]
Sure

**Comment by nervebassmaster** [comment]
Tests have been updated.
Some issues occurred but they were related to the old node.js instances (like 0.10 and 0.12).
Fixed for now.

**Comment by watson** [comment]
Thanks for the help 😃 This have now been released in v1.1.1

**Comment by artem-konovalov-personal** [comment]
thx :smiley:  :+1:

**Pull request merged**
